### ISSUE TITLE
Menu won't load

### ISSUE THREAD

**Issue by TimoBS** [kaelspencer/MMM-PaprikaMenu#6]
Hope somebody may have the same issue or could supply some help.
Somehow PaprikaMenu stop working for me and do not longer load the Menu and just shows "Loading ...". Can't find something in the logs and tried it also with the original example configuration with same results. 

Also not helping output from /home/pi/.pm2/logs/MagicMirror-out.log:
0|MagicMir | MMM-PaprikaMenu: Week starts: 2019-03-17, next week starts: 2019-03-24
0|MagicMir | MMM-PaprikaMenu: Waiting on 2 Paprika recipe calls.
0|MagicMir | MMM-PaprikaMenu: All recipe queries returned.
0|MagicMir | MMM-PaprikaMenu: Updating recipe
0|MagicMir | MMM-PaprikaMenu: Updating recipe

Thanks in advance!

**Comment by kaelspencer** [comment]
Logs seem to indicate that two recipes were pulled down so the issue must be after that. Can you look at the browser logs? Ctrl+shift+i brings up the developer tools. The Console tab shows logging statements. The right hand side lists the source file. Look for MMM-PaprikaMenu.js. Hopefully you see an error statement; otherwise, one of the last log statements just just be an object dump. What do you see?

**Comment by TimoBS** [comment]
Thanks for the quick response. Just had the chance to have a look to the browser logs.
At the console with keyword "Paprika" following output is generated:

loader.js:182 Load script: modules/MMM-PaprikaMenu//MMM-PaprikaMenu.js
module.js:469 Check MagicMirror version for module 'MMM-PaprikaMenu' - Minimum version:  2.2.0 - Current version: 2.6.0
module.js:477 Module registered: MMM-PaprikaMenu
loader.js:152 Bootstrapping module: MMM-PaprikaMenu
loader.js:157 Scripts loaded for: MMM-PaprikaMenu
loader.js:197 Load stylesheet: modules/MMM-PaprikaMenu/MMM-PaprikaMenu.css
loader.js:159 Styles loaded for: MMM-PaprikaMenu
loader.js:161 Translations loaded for: MMM-PaprikaMenu
MMM-PaprikaMenu.js:56 Starting module: MMM-PaprikaMenu
module.js:156 MMM-PaprikaMenu received a system notification: ALL_MODULES_STARTED
module.js:154 MMM-PaprikaMenu received a module notification: REGISTER_VOICE_MODULE from sender: MMM-Fuel
module.js:156 MMM-PaprikaMenu received a system notification: MODULE_DOM_CREATED
module.js:156 MMM-PaprikaMenu received a system notification: DOM_OBJECTS_CREATED
module.js:154 MMM-PaprikaMenu received a module notification: CURRENTWEATHER_DATA from sender: currentweather
MMM-PaprikaMenu.js:105 Uncaught TypeError: console.log is not a function
    at Class.socketNotificationReceived (MMM-PaprikaMenu.js:105)
    at module.js:246
    at r.<anonymous> (socketclient.js:25)
    at r.emit (index.js:83)
    at r.onevent (index.js:83)
    at r.MMSocket.self.socket.onevent (socketclient.js:19)
    at r.onpacket (index.js:83)
    at r.<anonymous> (index.js:83)
    at r.emit (index.js:83)
    at r.ondecoded (index.js:83)
socketNotificationReceived @ MMM-PaprikaMenu.js:105
(anonymous) @ module.js:246
(anonymous) @ socketclient.js:25
r.emit @ index.js:83
r.onevent @ index.js:83
MMSocket.self.socket.onevent @ socketclient.js:19
r.onpacket @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.ondecoded @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
a.add @ index.js:83
r.ondata @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onPacket @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onPacket @ index.js:83
r.onData @ index.js:83
ws.onmessage @ index.js:83
module.js:154 MMM-PaprikaMenu received a module notification: USER_PRESENCE from sender: MMM-PIR-Sensor

If I go to source file and look for MMM-PaprikaMenu.js I see the following error statement shown on attached screenshot.

![Bildschirmfoto 2019-03-19 um 17 17 34](https://user-images.githubusercontent.com/48655275/54622992-ede97680-4a6a-11e9-9d82-6c6c40ab9d6f.png)

**Comment by kaelspencer** [comment]
Well, this is quite strange indeed! Line 105 is just a logging statement, a normal console.log call. It probably could have been Log.info() instead; not sure why it isn't.

I'm not really a JavaScript expert, but my understanding is that something like this is _valid_ but bad:

`console.log = "foobar";`

Then when you call

`console.log("cats");`

You would get `Uncaught TypeError: console.log is not a function`. I suspect something in this realm happened because of how the red squiggles are under the .log portion in the image you shared.

By chance, did this start happening after you added a new module? If it did, I'd be curious about which module so I could look at their code.

In the meantime, you can just delete or comment out line 105. I'll look at swapping it to a Log.info when I get some time.

**Comment by TimoBS** [comment]
Did deactivate all additional third parties modules and activate them step by step.
Paprika stops working when the Module "MMM-GoogleMapsTraffic" was activated.

Afterwards I did comment out line 105 and activate "MMM-GoogleMapsTraffic" again.
Now both are working fine together and Paprika does load.

**Comment by TimoBS** [comment]
Spend some minutes and figure out that an issue is reported for "MMM-GoogleMapsTraffic" at https://github.com/vicmora/MMM-GoogleMapsTraffic/pull/24/commits/90f51f6f7a155241a4371106ea3ca899b20a7380.

If I comment out the mentioned line from module "MMM-GoogleMapsTraffic" Paprika does also work.
No more need for changes in Paprika. Question for me is only why different modules could influence each other is this way...

**Comment by kaelspencer** [comment]
Ah great, my suspicion was correct. Glad you have things working, and thanks for using the module!
